### ISSUE TITLE
some questions about data and figure 3d

### ISSUE THREAD

**Issue by yuling999666** [YiLab-SC/scHolography#16]

**Comment by yuling999666** [comment]
<img width="1377" alt="Screenshot 2024-12-18 at 7 29 15 PM" src="https://github.com/user-attachments/assets/6ba252f4-d6b4-4169-8a5f-aedb0e98ee9b" />
Hi, I have a question. When you made figure 3d, did you apply this tool (scHolograpgy) to process the data to make these slices align? I think the answer is no but just shifting coordinates of each slice according to the reference, since I didn't find it in analysis source code, but just some preprocessing about SCTransform, UMAP and PCA. I am curious about how you do 3d.Thanks.

**Comment by yuling999666** [comment]
Hi @cadyyuheng , did you only use spatial information to get stacked plot of figure 3d in paper? I checked your analysis code, it seems that you just shifted the coordinates according to the bottom slice? Thanks.

**Comment by cadyyuheng** [comment]
Hi @yuling999666 ,
Thanks for your interest in our scHolography paper. For the stacked-2D sample analysis, the coordinates of slices 310 and 500 were normalized using slice 400 as the reference, such as the coordinate median in all three samples being the same as slice 400. However, we also went beyond three slices. For cases shown in Figures S5 and S6, we used the “PASTE” package for pairwise slice alignment within each sample. I hope this helps clarify your question.

**Comment by yuling999666** [comment]
Hi @cadyyuheng , Thank you for clarification. It helps. So you didn't consider the relationship of gene expression data between slice 310 and slice 400 as well as slice 500 and slice 400 when stacking 2D sample in analysis for figure 3d? I have checked supplement figure S5 and S6 and I know "PASTE" does alignment considering gene expression data and spatial information. One more question just confirm that I understand your algorithm correctly: your method is about 3D spatial neighborhood reconstruction instead of generating a stacked 3D aligned slices of a tissue? It seems that the concept of doing 3D in your paper is not the same as the paper of "PASTE". Thank you for your time.

**Comment by yuling999666** [comment]
> Hi @yuling999666 , Thanks for your interest in our scHolography paper. For the stacked-2D sample analysis, the coordinates of slices 310 and 500 were normalized using slice 400 as the reference, such as the coordinate median in all three samples being the same as slice 400. However, we also went beyond three slices. For cases shown in Figures S5 and S6, we used the “PASTE” package for pairwise slice alignment within each sample. I hope this helps clarify your question.

Hi @cadyyuheng, In addition, I would like to ask I can just use one slice as reference, right? Thanks

**Comment by cadyyuheng** [comment]
> Hi @cadyyuheng , Thank you for clarification. It helps. So you didn't consider the relationship of gene expression data between slice 310 and slice 400 as well as slice 500 and slice 400 when stacking 2D sample in analysis for figure 3d? I have checked supplement figure S5 and S6 and I know "PASTE" does alignment considering gene expression data and spatial information. One more question just confirm that I understand your algorithm correctly: your method is about 3D spatial neighborhood reconstruction instead of generating a stacked 3D aligned slices of a tissue? It seems that the concept of doing 3D in your paper is not the same as the paper of "PASTE". Thank you for your time.

@yuling999666 ,Yes, Figure 3d did not consider any expression data when stacking slices together. I would like to clarify that the reason we include information like Figure 3d and paste results in Figures S5 and S6 is to establish a ground truth for validation. The stacked 2D information serves as the ground truth to compare with scHolography results, such as those shown in Figure 3e.

You are absolutely correct that our method focuses on neighborhood reconstruction, specifically for scRNA-seq data. The scHolography concept for 3D visualization is entirely different from "PASTE." In scHolography, we reconstruct scRNA-seq data using spatial transcriptomics (ST) data as a reference, whereas I consider PASTE to be an ST alignment method.

**Comment by cadyyuheng** [comment]
> > Hi @yuling999666 , Thanks for your interest in our scHolography paper. For the stacked-2D sample analysis, the coordinates of slices 310 and 500 were normalized using slice 400 as the reference, such as the coordinate median in all three samples being the same as slice 400. However, we also went beyond three slices. For cases shown in Figures S5 and S6, we used the “PASTE” package for pairwise slice alignment within each sample. I hope this helps clarify your question.
> 
> Hi @cadyyuheng, In addition, I would like to ask I can just use one slice as reference, right? Thanks

Yep, it uses a single ST slice as the reference.

**Comment by yuling999666** [comment]
> > > Hi @yuling999666 , Thanks for your interest in our scHolography paper. For the stacked-2D sample analysis, the coordinates of slices 310 and 500 were normalized using slice 400 as the reference, such as the coordinate median in all three samples being the same as slice 400. However, we also went beyond three slices. For cases shown in Figures S5 and S6, we used the “PASTE” package for pairwise slice alignment within each sample. I hope this helps clarify your question.
> > 
> > 
> > Hi @cadyyuheng, In addition, I would like to ask I can just use one slice as reference, right? Thanks
> 
> Yep, it uses a single ST slice as the reference.

Hi @cadyyuheng Thank you for illustration. It really helps.
